base_packages:
  - qemu-guest-agent
  - python3
  - python3-pip
  - python3-requests
  - python3-urllib3
  - python3-venv
  - rsync
  - tmux
  - vim

base_debian_packages:
  - dnsutils
  - gnupg
  - python3-apt

base_redhat_packages:
  - python3-dnf
  - python3-libselinux
