---
- name: add HashiCorp's apt gpg key
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg \
      | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: add HashiCorp's apt repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp

- name: install
  apt:
    name: terraform
    state: present
    update_cache: true
