---
- name: install docker prerequisites
  apt:
    name:
      - ca-certificates
      - curl
  tags:
    - portainer-agent
    - portainer-server

- name: create keyring directory /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  tags:
    - portainer-agent
    - portainer-server

- name: fetch docker GPG key to keyring
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0755"
  tags:
    - portainer-agent
    - portainer-server

- name: add docker repo to apt
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts.lsb.codename | default(ansible_facts.distribution_release) }} stable"
    filename: docker
    update_cache: true
  tags:
    - portainer-agent
    - portainer-server

- name: install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - python3-docker
  tags:
    - portainer-agent
    - portainer-server

# agent
- name: ensure portainer agent is running
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:2.33.2
    restart_policy: always
    published_ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    state: started
  tags:
    - portainer-agent

# server
# - name: ensure portainer data volume exists
#   community.docker.docker_volume:
#     name: portainer_data
#     state: present
#   tags:
#     - portainer-server

# - name: ensure portainer server is running
#   community.docker.docker_container:
#     name: portainer
#     image: portainer/portainer-ce:2.33.2
#     restart_policy: always
#     published_ports:
#       - "9443:9443"
#       - "8000:8000"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - portainer_data:/data
#     state: started
#   tags:
#     - portainer-server
