---
- name: update (apt)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"

- name: update (dnf/yum)
  dnf:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_pkg_mgr in ["dnf", "yum"]

- name: base packages
  package:
    name: "{{ item }}"
  loop: "{{ base_packages }}"

- name: install qemu
  package:
    name: "qemu-guest-agent"
  when: ansible_virtualization_type == "kvm"

- name: debian packages
  package:
    name: "{{ item }}"
  loop: "{{ base_debian_packages }}"
  when: ansible_os_family  == "Debian"

- name: redhat packages
  package:
    name: "{{ item }}"
  loop: "{{ base_redhat_packages }}"
  when: ansible_os_family  == "RedHat"
